Dbus/demos/demo_ruby/demo_ruby

Fix the "crash" when changing like:
./demo_ruby:108:in `reload': undefined local variable or method `myApplet' for #<Applet:0x00000002e6c060> (NameError)
from /usr/share/ruby/vendor_ruby/CDApplet.rb:203:in `_on_reload'
from /usr/share/ruby/vendor_ruby/CDApplet.rb:274:in `block in _connect_to_dock'
from /usr/share/gems/gems/ruby-dbus-0.9.0/lib/dbus/introspect.rb:325:in `call'
from /usr/share/gems/gems/ruby-dbus-0.9.0/lib/dbus/introspect.rb:325:in `block in on_signal'
from /usr/share/gems/gems/ruby-dbus-0.9.0/lib/dbus/bus.rb:665:in `call'
from /usr/share/gems/gems/ruby-dbus-0.9.0/lib/dbus/bus.rb:665:in `block in process'
from /usr/share/gems/gems/ruby-dbus-0.9.0/lib/dbus/bus.rb:663:in `each'
from /usr/share/gems/gems/ruby-dbus-0.9.0/lib/dbus/bus.rb:663:in `process'
from …

demo_ruby: fix traceback when changing themes

---

gvfs-integration/cairo-dock-gio-vfs.c

Well, I usually use LXDE so no integration plug-ins are enabled. Actually although cairo-dock settings shows "gnome-integration" icon, it is grayed out and when I
- add "logout" plugin
- choose "logout -> lock screen"
screen isn't locked.
However (I use LXDE on Fedora and) LXDE user installs xscreensaver and xdg-utils, and I guess other xscreensaver fans also use it on other DE users. As xdg-utils is maintained by freedesktop.org and xdg-screensaver lock chooses lock screen command (so when xscreensaver is running it actually launches xscreensaver-command -lock), I think it is preferable that lock_screen defauls to xdg-screensaver, when no integration plugin is activated.

RFE: Default to xdg-screensaver for lock_screen

---

weather/src/applet-config.c

The macro CD_WEATHER_HAS_CODE_LOCATION is currently undefined,
so cd_weather_free_location_list() symbol is not compiled in
libcd-weather.so .
So cd_weather_reset_all_datas() should not be called in
cd_weather_reset_all_datas().

Weather applet: fix missing symbol on libcd-weather.so

---

weather/src/applet-read-data.c

applet-read-data.c:362:2: error: unknown type name ‘uint’; did you mean ‘guint’?
362 |  uint md_len=64;
|  ^~~~
|  guint

hofix for build

---

dock-rendering/src/rendering-config.c

Comment in line 29, to avoid duplicate in definition of variable my_fRainbowColor. Affects previous versions of cairo-dock-plugins. Solved same issue in version 3.4.1 adding comment before definition of variables : my_fRainbowColor and my_fRainbowLineColor.

Double definition of my_fRainbowColor

---

Dbus/interfaces/vala/CMakeLists.txt

valac generates C source from vala source and outputs the result on the same directory as vala source.
But cmake working directory may be different
from the vala source directory. So to move generated source properly, specify the origination directory for mv command explicitly.

vala: move generated C source from vala source properly

---

Dbus/interfaces/bash/setup.py
Dbus/interfaces/python/setup.py

distutils is no more as of Python 3.12; setuptools is the simplest migration option [1] although it does add a dependency to the project
[1]: https://peps.python.org/pep-0632/#migration-advice

Use setuptools instead of distutils

---

Dbus/interfaces/vala/CMakeLists.txt

Seems to be required by f771b22 in some cases.

Dbus: use an explicit working directory for valac

---

Dbus/src/interface-applet-object.c

Fixes https://github.com/Cairo-Dock/cairo-dock-core/issues/66
Previously, this relied on cairo_dock_launch_command () using a shell which is not true anymore.

DBus: properly use the new API for launching external applets

---

CMakeLists.txt
Dbus/data/cairo-dock-launcher-API-daemon.py
Dbus/interfaces/python/CairoDock.py
gnome-integration/src/applet-init.c
gvfs-integration/cairo-dock-gio-vfs.c
logout/data/logout.conf.in
logout/src/applet-config.c
logout/src/applet-logout.c
logout/src/applet-struct.h

- gnome / gvfs: handle screen locking on Wayland better (xdg-screensaver does not work, loginctl might)
- logout: allow to set a custom command for locking the screen
- Dbus: run launcher-API-daemon only if it can connect to Cairo-Dock (and exit with the dock)

Improve desktop integration

---

GMenu/src/applet-entry.c

This allows e.g. running more complex custom commands

GMenu: allow typing spaces into the search entry

---

CMakeLists.txt
Dbus/src/applet-dbus.c
Dbus/src/interface-applet-object.c
GMenu/src/applet-apps.c
GMenu/src/applet-entry.c
GMenu/src/applet-notifications.c
GMenu/src/applet-run-dialog.c
GMenu/src/applet-struct.h
GMenu/src/applet-tree.c
Global-Menu/src/applet-app.c
RSSreader/src/applet-notifications.c
Recent-Events/src/applet-dialog.c
Recent-Events/src/applet-notifications.c
Remote-Control/src/applet-init.c
Scooby-Do/src/applet-appli-finder.c
Scooby-Do/src/applet-backend-firefox.c
Scooby-Do/src/applet-draw.c
Scooby-Do/src/applet-init.c
Scooby-Do/src/applet-listing.c
Scooby-Do/src/applet-notifications.c
Status-Notifier/src/applet-host.c
Status-Notifier/src/applet-notifications.c
gnome-integration/src/applet-utils.c
gvfs-integration/cairo-dock-gio-vfs.c
kde-integration/src/applet-utils.c
kde-integration/src/applet-vfs.c
logout/src/applet-logout.c
netspeed/src/applet-notifications.c
shortcuts/src/applet-notifications.c

Use the new APIs for launching apps and commands in the most important places.
Additional small improvements:
- Scooby-do: fix some rendering issues
- Global-Menu: support Qt apps on KWin Wayland
- Remote-Control: enable on Wayfire, use the toggle_menu signal to start it

Adapt plugins to core + small improvements

---

CMakeLists.txt

No changes, this is only to make packaging easier (core will only load plugins that have been compiled with the same minor version, so updating core will require a recompile of plugins anyway).

bump version to be in sync with core

---

kde-integration/src/applet-utils.c

Fixes https://github.com/Cairo-Dock/cairo-dock-core/issues/87
It seems that `kioclient` is only versioned on KDE5.

kde-integration: adapt to work on KDE6

---

CMakeLists.txt
Recent-Events/src/applet-dialog.c
switcher/src/applet-draw.c

This fixes blurry icons in switcher's window list menu and Recent-Event's list view. Depends on https://github.com/Cairo-Dock/cairo-dock-core/pull/98

HiDPI fixes for switcher and Recent-Events

---

switcher/src/applet-load-icons.c

On Wayland we typically cannot find a desktop background, so avoid spamming the output every time the desktop is updated.

switcher: only warn about missing background once

---

CMakeLists.txt

The `pkgdatadir` variable from core is required for properly displaying some icons in the settings GUI.

Fix missing icons in GUI

---

dock-rendering/src/rendering-3D-plane.c
dock-rendering/src/rendering-curve.c

This is to avoid docks being 1 pixel smaller than need to be and cutting off the top of labels.

dock-rendering: round up in dock size calculations

---

dock-rendering/src/rendering-slide.c

When rendering with OpenGL, we need to take into account the scale factor.
Fixes https://github.com/Cairo-Dock/cairo-dock-core/issues/134

dock-rendering/slide: fix rendering when icons do not fit in the subdock

---

CMakeLists.txt
Dbus/src/interface-applet-signals.c
Dbus/src/interface-applet-signals.h
desklet-rendering/src/rendering-desklet-viewport.c
dock-rendering/src/rendering-slide.c

This adds smooth scrolling support for subdocks (slide) and desklets (viewport) + updates signal handler prototypes where necessary

Smooth scrolling support

---

Composite-Manager/src/applet-notifications.c
Dbus/src/applet-dbus.c
Dbus/src/interface-applet-methods.c
Dbus/src/interface-applet-signals.c
GMenu/src/applet-apps.c
GMenu/src/applet-entry.c
GMenu/src/applet-init.c
GMenu/src/applet-run-dialog.c
GMenu/src/applet-tree.c
Recent-Events/src/applet-notifications.c
Remote-Control/src/applet-init.c
gvfs-integration/cairo-dock-gio-vfs.c
logout/src/applet-logout.c
switcher/src/applet-notifications.c

This is a feature only introduced in C23 and is not supported on older compilers. Fixes https://github.com/Cairo-Dock/cairo-dock-core/issues/147

Fix the use of unnamed function parameters
